-d C:\Users\elian\Desktop\TP4 PB Tudo FUNCIONANDO\Projeto_TP4 Ok\VERILOG OK\fpga_project_pb_tp4_funcionando_100_00\impl\gwsynthesis\fpga_project_pb_tp4.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst C:\Users\elian\Desktop\TP4 PB Tudo FUNCIONANDO\Projeto_TP4 Ok\VERILOG OK\fpga_project_pb_tp4_funcionando_100_00\src\projtp3.cst
-cfg C:\Users\elian\Desktop\TP4 PB Tudo FUNCIONANDO\Projeto_TP4 Ok\VERILOG OK\fpga_project_pb_tp4_funcionando_100_00\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
